---
title: "DW_Graphs"
author: "Huy Nguyen"
date: "2022-07-20"
output: html_document
---

Load Data
```{r}
library(readxl)
library(tidyverse)
library(psych)

dat = readRDS("DW.rds")
```

Clean Data
```{r}
nuDat = dat %>% 
  group_by(Status) %>%
  summarise(
    n = n(),
    #Mean 
    mLatency = mean(Latency),
    mHide = mean(tHide),
    mExit = mean(nExit),
    #SD
    sdLatency = sd(Latency),
    sdHide = sd(tHide),
    sdExit = sd(nExit)
  ) %>%
  mutate(
    #SE
    seLatency = sdLatency / sqrt(n),
    seHide= sdHide / sqrt(n),
    seExit = sdExit / sqrt(n)
  )
```

###Graphing
```{r}
Graphs = list(LL = NA, Hide = NA, Exit = NA)
```

####Leave Latency
```{r}
Graphs$LL = ggplot(data = nuDat, aes(x = Status, y = mLatency, fill = Status))+
  geom_col()+
  geom_errorbar( aes(x = Status, ymin = mLatency - seLatency, ymax = mLatency + seLatency), width = 0.4, alpha = 0.9)+
  coord_flip()+
  theme_classic()+
  theme(plot.title = element_text(face = "bold"), axis.title.y = element_blank(), legend.position = "none")+
  scale_y_continuous(name="Mean Time (sec)")+
  labs(title="Mean Latency to Exit Safe Box")
Graphs$LL

export::graph2png(Graphs$LL, "C:/Users/Test/OneDrive/SPU/Independent Research/Baker/Predator & Decision-making/H Cohort/FINAL/Graphs/DW/LeaveLatency")
```

####Hide
```{r}
Graphs$Hide = ggplot(data = nuDat, aes(x = Status, y = mHide, fill = Status))+
  geom_col()+
  geom_errorbar( aes(x = Status, ymin = mHide - seHide, ymax = mHide + seHide), width = 0.4, alpha = 0.9)+
  coord_flip()+
  theme_classic()+
  theme(plot.title = element_text(face = "bold"), axis.title.y = element_blank(), legend.position = "none")+
  scale_y_continuous(name="Mean Time (sec)")+
  labs(title="Mean Time in Safe Box")
Graphs$Hide

export::graph2png(Graphs$Hide, "C:/Users/Test/OneDrive/SPU/Independent Research/Baker/Predator & Decision-making/H Cohort/FINAL/Graphs/DW/Hide")
```

####Exit 
```{r}
Graphs$Exit = ggplot(data = nuDat, aes(x = Status, y = mExit, fill = Status))+
  geom_col()+
  geom_errorbar( aes(x = Status, ymin = mExit - seExit, ymax = mExit + seExit), width = 0.4, alpha = 0.9)+
  theme_classic()+
  theme(plot.title = element_text(face = "bold"), axis.title.x = element_blank(), legend.position = "none")+
  scale_y_continuous(name="Count")+
  labs(title="Mean Safe Box Exits")
Graphs$Exit

export::graph2png(Graphs$Exit, "C:/Users/Test/OneDrive/SPU/Independent Research/Baker/Predator & Decision-making/H Cohort/FINAL/Graphs/DW/Exit")
```

