---
title: "Marble_Graph"
author: "Huy Nguyen"
date: "2022-07-27"
output: html_document
---

Load Data
```{r}
library(readxl)
library(tidyverse)
library(psych)
library(ggpubr)
library(ggmap)
library(ggrepel)
library(export)

dat = readRDS("M.rds")
```

Clean Data
```{r}
nuDat = dat %>% 
  group_by(Status) %>%
  summarise(
    n = n(),
    #Mean 
    meanMarble = mean(mMarble),
    #SD
    sdMarble = sd(mMarble)
  ) %>%
  mutate(
    #SE
    seMarble = sdMarble / sqrt(n)
  )
```

#### Graphing
```{r}
#Buried Marble
Buried = ggplot(data = nuDat, aes(x = Status, y = meanMarble, fill = Status))+
  geom_col()+
  geom_errorbar( aes(x = Status, ymin = meanMarble - seMarble, ymax = meanMarble + seMarble), width = 0.4, alpha = 0.9)+
  theme_classic()+
  labs(title="Mean Percentage of Marble Buried")+
  theme(plot.title = element_text(face = "bold"), legend.position = "none")+
  scale_y_continuous(name="Mean Percentage")
Buried

export::graph2png(Buried, "C:/Users/Test/OneDrive/SPU/Independent Research/Baker/Predator & Decision-making/H Cohort/FINAL/Graphs/M/Buried")
```

#### **PIE CHART**
```{r}
dataPie = dat[, c("Status", "tStand", "tGroom", "tDig", "tChew")] 

SUM_TIME_M = 4*20*60 #number of rats * 20 minutes * seconds in minute
SUM_TIME_F = 5*20*60
  
pie = dataPie %>% 
  group_by(Status) %>%
  summarise(
    Stand = sum(tStand),
    Groom =sum(tGroom),
    Dig = sum(tDig),
    Chew = sum(tChew)
  ) %>%
  pivot_longer(c("Stand", "Groom", "Dig", "Chew"), names_to = "behavior", values_to = "sumTime") 
```

#### Male_Control
```{r}

pieMC = pie %>% filter(Status == "Male_Control")

valNA = SUM_TIME_M - (sum(pieMC$sumTime))

pieMC = pieMC %>%
  add_row(Status = "Male_Control", behavior = "Others", sumTime = valNA) %>%
  mutate(
    perc = sumTime / SUM_TIME_M,
    labels = scales::percent(perc)
  ) %>% 
  arrange(match(behavior, c("Stand", "Others", "Groom", "Dig", "Chew"))) %>%
  mutate( 
    text_y = cumsum(sumTime) - sumTime/2
  ) 
```

#### **Graphing**
```{r}
# Male_Control
pie_MC = ggplot(data = pieMC, aes(x = 1, y = sumTime, fill = behavior))+
  geom_col()+
  theme_void()+
  scale_fill_manual(values = c("#3C3249", "#334E58", "#078B9C", "#60A63A", "#DAE2A1"))+
  coord_polar(theta = "y", start = 0)+
  geom_label_repel(aes(label = paste(behavior, "\n", labels), y = text_y), nudge_x = 0.8, color = c("Black", "White", "White", "White", "White"))+
  theme(legend.position = "none", plot.title = element_text(hjust = 0.3, face = "bold"), plot.subtitle = element_text(hjust = 0.3))+
  labs(title="Mean Behavior Distribution",
       subtitle="Male Control Group")
pie_MC

export::graph2png(pie_MC, "C:/Users/Test/OneDrive/SPU/Independent Research/Baker/Predator & Decision-making/H Cohort/FINAL/Graphs/M/Male_Control")
```

#### Male_Owl
```{r}
pieMO = pie %>% filter(Status == "Male_Owl")

valNA_1 = SUM_TIME_F - (sum(pieMO$sumTime))

pieMO = pieMO %>%
  add_row(Status = "Male_Owl", behavior = "Others", sumTime = valNA_1) %>%
  mutate(
    perc = sumTime / SUM_TIME_F,
    labels = scales::percent(perc)
  ) %>% 
  arrange(match(behavior, c("Stand", "Others", "Groom", "Dig", "Chew"))) %>%
  mutate( 
    text_y = cumsum(sumTime) - sumTime/2
  ) 
```

#### **Graphing**
```{r}
# Male_Owl
pie_MO = ggplot(data = pieMO, aes(x = 1, y = sumTime, fill = behavior))+
  geom_col()+
  theme_void()+
  scale_fill_manual(values = c("#3C3249", "#334E58", "#078B9C", "#60A63A", "#DAE2A1"))+
  coord_polar(theta = "y", start = 0)+
  geom_label_repel(aes(label = paste(behavior, "\n", labels), y = text_y), nudge_x = 0.8, color = c("Black", "White", "White", "White", "White"))+
  theme(legend.position = "none", plot.title = element_text(hjust = 0.3, face = "bold"), plot.subtitle = element_text(hjust = 0.3))+
  labs(title="Mean Behavior Distribution",
       subtitle="Male Owl Group")
pie_MO

export::graph2png(Graphs$pie_MO, "C:/Users/Test/OneDrive/SPU/Independent Research/Baker/Predator & Decision-making/H Cohort/FINAL/Graphs/M/Male_Owl")
```

#### Female_Control
```{r}
pieFC = pie %>% filter(Status == "Female_Control")

valNA_2 = SUM_TIME_F - (sum(pieFC$sumTime))

pieFC = pieFC %>%
  add_row(Status = "Female_Control", behavior = "Others", sumTime = valNA_2) %>%
  mutate(
    perc = sumTime / SUM_TIME_F,
    labels = scales::percent(perc)
  ) %>% 
  arrange(match(behavior, c("Stand", "Others", "Groom", "Dig", "Chew"))) %>%
  mutate( 
    text_y = cumsum(sumTime) - sumTime/2
  ) 
```

#### **Graphing**
```{r}
# Female_Control
pie_FC = ggplot(data = pieFC, aes(x = 1, y = sumTime, fill = behavior))+
  geom_col()+
  theme_void()+
  scale_fill_manual(values = c("#3C3249", "#334E58", "#078B9C", "#60A63A", "#DAE2A1"))+
  coord_polar(theta = "y", start = 0)+
  geom_label_repel(aes(label = paste(behavior, "\n", labels), y = text_y), nudge_x = 0.8, color = c("Black", "White", "White", "White", "White"))+
  theme(legend.position = "none", plot.title = element_text(hjust = 0.3, face = "bold"), plot.subtitle = element_text(hjust = 0.3))+
  labs(title="Mean Behavior Distribution",
       subtitle="Female Control Group")
pie_FC

export::graph2png(Graphs$pie_FC, "C:/Users/Test/OneDrive/SPU/Independent Research/Baker/Predator & Decision-making/H Cohort/FINAL/Graphs/M/Female_Control")
```

#### Female_Owl
```{r}
pieFO = pie %>% filter(Status == "Female_Owl")

valNA_2 = SUM_TIME_F - (sum(pieFO$sumTime))

pieFO = pieFO %>%
  add_row(Status = "Female_Owl", behavior = "Others", sumTime = valNA_2) %>%
  mutate(
    perc = sumTime / SUM_TIME_F,
    labels = scales::percent(perc)
  ) %>% 
  arrange(match(behavior, c("Stand", "Others", "Groom", "Dig", "Chew"))) %>%
  mutate( 
    text_y = cumsum(sumTime) - sumTime/2
  ) 
```

#### **Graphing**
```{r}
# Female_Owl
pie_FO = ggplot(data = pieFO, aes(x = 1, y = sumTime, fill = behavior))+
  geom_col()+
  theme_void()+
  scale_fill_manual(values = c("#3C3249", "#334E58", "#078B9C", "#60A63A", "#DAE2A1"))+
  coord_polar(theta = "y", start = 0)+
  geom_label_repel(aes(label = paste(behavior, "\n", labels), y = text_y), nudge_x = 0.8, color = c("Black", "White", "White", "White", "White"))+
  theme(legend.position = "none", plot.title = element_text(hjust = 0.3, face = "bold"), plot.subtitle = element_text(hjust = 0.3))+
  labs(title="Mean Behavior Distribution",
       subtitle="Female Owl Group")
pie_FO

export::graph2png(Graphs$pie_FO, "C:/Users/Test/OneDrive/SPU/Independent Research/Baker/Predator & Decision-making/H Cohort/FINAL/Graphs/M/Female_Owl")
```